import { Product, Brand } from '@/types';

export const BRANDS: Brand[] = [
  {
    id: 'growth-supplements',
    name: 'Growth Supplements',
    website: 'https://www.gsuplementos.com.br',
    active: true,
    coupon: 'BRIGADEIRO',
  },
  {
    id: 'oficial-farma',
    name: 'Oficial Farma',
    website: 'https://www.oficialfarma.com.br',
    active: true,
    coupon: 'BRIGADEIRO',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    "id": "gw-1",
    "brand_id": "growth-supplements",
    "brand": "Growth Supplements",
    "name": "Whey Protein concentrado",
    "slug": "whey-protein-concentrado-growth",
    "category": "Suplementos Esportivos",
    "description": "Whey Protein concentrado da Growth Supplements, formulado para alta pureza e desempenho.",
    "indication": "Todos",
    "usage_instruction": "misturar 2 dosadores com água",
    "ingredients": "Consulte a embalagem oficial para lista completa de ingredientes.",
    "warnings": "Não exceder a recomendação diária de consumo indicada na embalagem.",
    "restrictions": "Alérgicos: consulte a lista de ingredientes no site oficial.",
    "image_url": "",
    "url": "https://www.gsuplementos.com.br/whey-protein-concentrado-1kg-growth-supplements-p985936",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 10,
    "equivalent_slug": null,
    "tags": [
      "saude_geral"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "gw-2",
    "brand_id": "growth-supplements",
    "brand": "Growth Supplements",
    "name": "Whey Protein Gourmet",
    "slug": "whey-protein-gourmet-growth",
    "category": "Suplementos Esportivos",
    "description": "Whey Protein Gourmet da Growth Supplements, formulado para alta pureza e desempenho.",
    "indication": "Todos",
    "usage_instruction": "misturar 2 e 1/2 dosadores com água",
    "ingredients": "Consulte a embalagem oficial para lista completa de ingredientes.",
    "warnings": "Não exceder a recomendação diária de consumo indicada na embalagem.",
    "restrictions": "Alérgicos: consulte a lista de ingredientes no site oficial.",
    "image_url": "",
    "url": "https://www.gsuplementos.com.br/whey-gourmet-tiramisu",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 10,
    "equivalent_slug": null,
    "tags": [
      "saude_geral"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "gw-3",
    "brand_id": "growth-supplements",
    "brand": "Growth Supplements",
    "name": "Whey Protein Zero Lactose",
    "slug": "whey-protein-zero-lactose-growth",
    "category": "Suplementos Esportivos",
    "description": "Whey Protein Zero Lactose da Growth Supplements, formulado para alta pureza e desempenho.",
    "indication": "Todos com intolerância à lactose",
    "usage_instruction": "misturar 2 dosadores com água",
    "ingredients": "Consulte a embalagem oficial para lista completa de ingredientes.",
    "warnings": "Não exceder a recomendação diária de consumo indicada na embalagem.",
    "restrictions": "Alérgicos: consulte a lista de ingredientes no site oficial.",
    "image_url": "",
    "url": "https://www.gsuplementos.com.br/whey-protein-zero-lactose",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 10,
    "equivalent_slug": null,
    "tags": [
      "lactose",
      "saude_geral"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "gw-4",
    "brand_id": "growth-supplements",
    "brand": "Growth Supplements",
    "name": "Soy Protein",
    "slug": "soy-protein-growth",
    "category": "Suplementos Esportivos",
    "description": "Soy Protein da Growth Supplements, formulado para alta pureza e desempenho.",
    "indication": "Todos veganos ou vegetarianos, alérgicos a leite",
    "usage_instruction": "misturar 2 dosadores com água",
    "ingredients": "Consulte a embalagem oficial para lista completa de ingredientes.",
    "warnings": "Não exceder a recomendação diária de consumo indicada na embalagem.",
    "restrictions": "Alérgicos: consulte a lista de ingredientes no site oficial.",
    "image_url": "",
    "url": "https://www.gsuplementos.com.br/soy-protein-proteina-isolada-de-soja-1kg-growth-supplements-p988010",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 5,
    "equivalent_slug": null,
    "tags": [
      "vegano",
      "saude_geral"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "gw-5",
    "brand_id": "growth-supplements",
    "brand": "Growth Supplements",
    "name": "Creatina",
    "slug": "creatina-growth",
    "category": "Suplementos Esportivos",
    "description": "Creatina da Growth Supplements, formulado para alta pureza e desempenho.",
    "indication": "Todos",
    "usage_instruction": "misturar 4 dosadores com água ou suco",
    "ingredients": "Consulte a embalagem oficial para lista completa de ingredientes.",
    "warnings": "Não exceder a recomendação diária de consumo indicada na embalagem.",
    "restrictions": "Alérgicos: consulte a lista de ingredientes no site oficial.",
    "image_url": "",
    "url": "https://www.gsuplementos.com.br/creatina-monohidratada-250gr-growth-supplements-p985931",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 10,
    "equivalent_slug": null,
    "tags": [
      "hipertrofia",
      "saude_geral"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "gw-6",
    "brand_id": "growth-supplements",
    "brand": "Growth Supplements",
    "name": "Pré Treino Haze",
    "slug": "pre-treino-haze-growth",
    "category": "Suplementos Esportivos",
    "description": "Pré Treino Haze da Growth Supplements, formulado para alta pureza e desempenho.",
    "indication": "Todos",
    "usage_instruction": "misturar 1 e 1/2 dosadores com 200ml de água",
    "ingredients": "Consulte a embalagem oficial para lista completa de ingredientes.",
    "warnings": "Não exceder a recomendação diária de consumo indicada na embalagem.",
    "restrictions": "Alérgicos: consulte a lista de ingredientes no site oficial.",
    "image_url": "",
    "url": "https://www.gsuplementos.com.br/pre-treino-haze-hardcore-300gr-growth-supplements",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 5,
    "equivalent_slug": null,
    "tags": [
      "saude_geral"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "gw-7",
    "brand_id": "growth-supplements",
    "brand": "Growth Supplements",
    "name": "Multivitamínico Ultra",
    "slug": "multivitaminico-ultra-growth",
    "category": "Suplementos Esportivos",
    "description": "Multivitamínico Ultra da Growth Supplements, formulado para alta pureza e desempenho.",
    "indication": "Todos",
    "usage_instruction": "1 comprimido ao dia junto com o almoço",
    "ingredients": "Consulte a embalagem oficial para lista completa de ingredientes.",
    "warnings": "Não exceder a recomendação diária de consumo indicada na embalagem.",
    "restrictions": "Alérgicos: consulte a lista de ingredientes no site oficial.",
    "image_url": "",
    "url": "https://www.gsuplementos.com.br/multivitaminico-ultra-120comp-growth-supplements",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 5,
    "equivalent_slug": null,
    "tags": [
      "saude_geral"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "gw-8",
    "brand_id": "growth-supplements",
    "brand": "Growth Supplements",
    "name": "Óleo de Peixe Ultra",
    "slug": "oleo-de-peixe-ultra-growth",
    "category": "Suplementos Esportivos",
    "description": "Óleo de Peixe Ultra da Growth Supplements, formulado para alta pureza e desempenho.",
    "indication": "Todos",
    "usage_instruction": "2 cápsulas ao dia junto com o almoço",
    "ingredients": "Consulte a embalagem oficial para lista completa de ingredientes.",
    "warnings": "Não exceder a recomendação diária de consumo indicada na embalagem.",
    "restrictions": "Alérgicos: consulte a lista de ingredientes no site oficial.",
    "image_url": "",
    "url": "https://www.gsuplementos.com.br/oleo-de-peixe-ultra-75-softgel-growth-supplements-p987568",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 5,
    "equivalent_slug": "omega-3",
    "tags": [
      "saude_geral"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "gw-9",
    "brand_id": "growth-supplements",
    "brand": "Growth Supplements",
    "name": "Vitamina C Ultra",
    "slug": "vitamina-c-ultra-growth",
    "category": "Suplementos Esportivos",
    "description": "Vitamina C Ultra da Growth Supplements, formulado para alta pureza e desempenho.",
    "indication": "Todos",
    "usage_instruction": "1 comprimido ao dia",
    "ingredients": "Consulte a embalagem oficial para lista completa de ingredientes.",
    "warnings": "Não exceder a recomendação diária de consumo indicada na embalagem.",
    "restrictions": "Alérgicos: consulte a lista de ingredientes no site oficial.",
    "image_url": "",
    "url": "https://www.gsuplementos.com.br/vitamina-c-1000mg-120comp-growth-supplements",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 5,
    "equivalent_slug": null,
    "tags": [
      "saude_geral"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "gw-10",
    "brand_id": "growth-supplements",
    "brand": "Growth Supplements",
    "name": "Vitamina D3 Ultra",
    "slug": "vitamina-d3-ultra-growth",
    "category": "Suplementos Esportivos",
    "description": "Vitamina D3 Ultra da Growth Supplements, formulado para alta pureza e desempenho.",
    "indication": "Todos",
    "usage_instruction": "1 comprimido junto ao almoço e 1 comprimido junto a janta",
    "ingredients": "Consulte a embalagem oficial para lista completa de ingredientes.",
    "warnings": "Não exceder a recomendação diária de consumo indicada na embalagem.",
    "restrictions": "Alérgicos: consulte a lista de ingredientes no site oficial.",
    "image_url": "",
    "url": "https://www.gsuplementos.com.br/vitamina-d-2000ui-120-caps-growth-supplements-p988066",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 5,
    "equivalent_slug": null,
    "tags": [
      "saude_geral"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "gw-11",
    "brand_id": "growth-supplements",
    "brand": "Growth Supplements",
    "name": "Vitamina K2",
    "slug": "vitamina-k2-growth",
    "category": "Suplementos Esportivos",
    "description": "Vitamina K2 da Growth Supplements, formulado para alta pureza e desempenho.",
    "indication": "Todos que tomarem a D3 Ultra",
    "usage_instruction": "1 cápsula junto ao almoço",
    "ingredients": "Consulte a embalagem oficial para lista completa de ingredientes.",
    "warnings": "Não exceder a recomendação diária de consumo indicada na embalagem.",
    "restrictions": "Alérgicos: consulte a lista de ingredientes no site oficial.",
    "image_url": "",
    "url": "https://www.gsuplementos.com.br/vitamina-k2-60-capsulas-growth-supplements",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 5,
    "equivalent_slug": null,
    "tags": [
      "saude_geral"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "gw-12",
    "brand_id": "growth-supplements",
    "brand": "Growth Supplements",
    "name": "Glutamina",
    "slug": "glutamina-growth",
    "category": "Suplementos Esportivos",
    "description": "Glutamina da Growth Supplements, formulado para alta pureza e desempenho.",
    "indication": "Todos com problemas no intestino e estômago.",
    "usage_instruction": "1 dosador com água ao acordar e antes de dormir",
    "ingredients": "Consulte a embalagem oficial para lista completa de ingredientes.",
    "warnings": "Não exceder a recomendação diária de consumo indicada na embalagem.",
    "restrictions": "Alérgicos: consulte a lista de ingredientes no site oficial.",
    "image_url": "",
    "url": "",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 5,
    "equivalent_slug": null,
    "tags": [
      "digestao",
      "saude_geral"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "gw-13",
    "brand_id": "growth-supplements",
    "brand": "Growth Supplements",
    "name": "Picolinato de Cromo",
    "slug": "picolinato-de-cromo-growth",
    "category": "Suplementos Esportivos",
    "description": "Picolinato de Cromo da Growth Supplements, formulado para alta pureza e desempenho.",
    "indication": "Emagrecimento e compulsão por doces",
    "usage_instruction": "1 comprimido ao dia junto do almoço",
    "ingredients": "Consulte a embalagem oficial para lista completa de ingredientes.",
    "warnings": "Não exceder a recomendação diária de consumo indicada na embalagem.",
    "restrictions": "Alérgicos: consulte a lista de ingredientes no site oficial.",
    "image_url": "",
    "url": "https://www.gsuplementos.com.br/picolinato-de-cromo-ultra-120-comp-growth-supplements",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 5,
    "equivalent_slug": null,
    "tags": [
      "emagrecimento"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "gw-14",
    "brand_id": "growth-supplements",
    "brand": "Growth Supplements",
    "name": "Psylium",
    "slug": "psylium-growth",
    "category": "Suplementos Esportivos",
    "description": "Psylium da Growth Supplements, formulado para alta pureza e desempenho.",
    "indication": "Emagrecimento e constipação",
    "usage_instruction": "1 dosador com água 30minutos antes do almoço e da janta",
    "ingredients": "Consulte a embalagem oficial para lista completa de ingredientes.",
    "warnings": "Não exceder a recomendação diária de consumo indicada na embalagem.",
    "restrictions": "Alérgicos: consulte a lista de ingredientes no site oficial.",
    "image_url": "",
    "url": "https://www.gsuplementos.com.br/100-psyllium-320gr-growth-supplements",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 5,
    "equivalent_slug": "psyllium",
    "tags": [
      "emagrecimento"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "gw-15",
    "brand_id": "growth-supplements",
    "brand": "Growth Supplements",
    "name": "Chá Verde",
    "slug": "cha-verde-growth",
    "category": "Suplementos Esportivos",
    "description": "Chá Verde da Growth Supplements, formulado para alta pureza e desempenho.",
    "indication": "Emagrecimento",
    "usage_instruction": "misturar 1 dosadore com 200ml de água, de manhã e a tarde",
    "ingredients": "Consulte a embalagem oficial para lista completa de ingredientes.",
    "warnings": "Não exceder a recomendação diária de consumo indicada na embalagem.",
    "restrictions": "Alérgicos: consulte a lista de ingredientes no site oficial.",
    "image_url": "",
    "url": "https://www.gsuplementos.com.br/cha-verde-200g-instantaneo-sabor-natural-growth-supplements-p985859",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 5,
    "equivalent_slug": "cha-verde",
    "tags": [
      "emagrecimento"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "gw-16",
    "brand_id": "growth-supplements",
    "brand": "Growth Supplements",
    "name": "Coenzima Q10 100mg",
    "slug": "coenzima-q10-100mg-growth",
    "category": "Suplementos Esportivos",
    "description": "Coenzima Q10 100mg da Growth Supplements, formulado para alta pureza e desempenho.",
    "indication": "Melhora da disposição e usuarios de estatinas",
    "usage_instruction": "1 comprimido ao dia",
    "ingredients": "Consulte a embalagem oficial para lista completa de ingredientes.",
    "warnings": "Não exceder a recomendação diária de consumo indicada na embalagem.",
    "restrictions": "Alérgicos: consulte a lista de ingredientes no site oficial.",
    "image_url": "",
    "url": "",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 5,
    "equivalent_slug": "coenzima-q10",
    "tags": [],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "gw-17",
    "brand_id": "growth-supplements",
    "brand": "Growth Supplements",
    "name": "N Acetil Cisteína",
    "slug": "n-acetil-cisteina-growth",
    "category": "Suplementos Esportivos",
    "description": "N Acetil Cisteína da Growth Supplements, formulado para alta pureza e desempenho.",
    "indication": "Melhora da Saúde Geral",
    "usage_instruction": "1 comprimido junto ao jantar, por 90 dias",
    "ingredients": "Consulte a embalagem oficial para lista completa de ingredientes.",
    "warnings": "Não exceder a recomendação diária de consumo indicada na embalagem.",
    "restrictions": "Alérgicos: consulte a lista de ingredientes no site oficial.",
    "image_url": "",
    "url": "https://www.gsuplementos.com.br/nac-n-acetil-l-cisteina-60caps-growth-supplements",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 5,
    "equivalent_slug": "nac-cisteina",
    "tags": [],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "gw-18",
    "brand_id": "growth-supplements",
    "brand": "Growth Supplements",
    "name": "Lactase",
    "slug": "lactase-growth",
    "category": "Suplementos Esportivos",
    "description": "Lactase da Growth Supplements, formulado para alta pureza e desempenho.",
    "indication": "Intolerantes a lactose",
    "usage_instruction": "1 comprimido 30min antes de ingerir qualquer alimento com lactose",
    "ingredients": "Consulte a embalagem oficial para lista completa de ingredientes.",
    "warnings": "Não exceder a recomendação diária de consumo indicada na embalagem.",
    "restrictions": "Alérgicos: consulte a lista de ingredientes no site oficial.",
    "image_url": "",
    "url": "",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 5,
    "equivalent_slug": null,
    "tags": [
      "lactose"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "gw-19",
    "brand_id": "growth-supplements",
    "brand": "Growth Supplements",
    "name": "Hipercalórico Big Mass",
    "slug": "hipercalorico-big-mass-growth",
    "category": "Suplementos Esportivos",
    "description": "Hipercalórico Big Mass da Growth Supplements, formulado para alta pureza e desempenho.",
    "indication": "Pessoas com dificuldade de Ganho de Peso",
    "usage_instruction": "misturar 9 dosadores com água",
    "ingredients": "Consulte a embalagem oficial para lista completa de ingredientes.",
    "warnings": "Não exceder a recomendação diária de consumo indicada na embalagem.",
    "restrictions": "Alérgicos: consulte a lista de ingredientes no site oficial.",
    "image_url": "",
    "url": "https://www.gsuplementos.com.br/big-mass-hipercalorico-3kgs-growth-supplements",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 5,
    "equivalent_slug": null,
    "tags": [],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "gw-20",
    "brand_id": "growth-supplements",
    "brand": "Growth Supplements",
    "name": "Complexo B",
    "slug": "complexo-b-growth",
    "category": "Suplementos Esportivos",
    "description": "Complexo B da Growth Supplements, formulado para alta pureza e desempenho.",
    "indication": "Todos veganos ou vegetarianos",
    "usage_instruction": "1 cápsula ao dia",
    "ingredients": "Consulte a embalagem oficial para lista completa de ingredientes.",
    "warnings": "Não exceder a recomendação diária de consumo indicada na embalagem.",
    "restrictions": "Alérgicos: consulte a lista de ingredientes no site oficial.",
    "image_url": "",
    "url": "",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 5,
    "equivalent_slug": "complexo-b",
    "tags": [
      "vegano",
      "saude_geral"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "gw-21",
    "brand_id": "growth-supplements",
    "brand": "Growth Supplements",
    "name": "Colágeno Tipo II",
    "slug": "colageno-tipo-ii-growth",
    "category": "Suplementos Esportivos",
    "description": "Colágeno Tipo II da Growth Supplements, formulado para alta pureza e desempenho.",
    "indication": "Pessoas com dores e lesões articulações",
    "usage_instruction": "1 cápsula ao dia",
    "ingredients": "Consulte a embalagem oficial para lista completa de ingredientes.",
    "warnings": "Não exceder a recomendação diária de consumo indicada na embalagem.",
    "restrictions": "Alérgicos: consulte a lista de ingredientes no site oficial.",
    "image_url": "",
    "url": "https://www.gsuplementos.com.br/colageno-tipo-2-60-capsulas-growth-supplements",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 5,
    "equivalent_slug": "saude-articular",
    "tags": [],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "gw-22",
    "brand_id": "growth-supplements",
    "brand": "Growth Supplements",
    "name": "Cranberry",
    "slug": "cranberry-growth",
    "category": "Suplementos Esportivos",
    "description": "Cranberry da Growth Supplements, formulado para alta pureza e desempenho.",
    "indication": "Mulheres com infecção urinaria recorrente",
    "usage_instruction": "2 capsulas ao dia",
    "ingredients": "Consulte a embalagem oficial para lista completa de ingredientes.",
    "warnings": "Não exceder a recomendação diária de consumo indicada na embalagem.",
    "restrictions": "Alérgicos: consulte a lista de ingredientes no site oficial.",
    "image_url": "",
    "url": "",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 5,
    "equivalent_slug": null,
    "tags": [],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "gw-23",
    "brand_id": "growth-supplements",
    "brand": "Growth Supplements",
    "name": "Colágeno + Vitaminas",
    "slug": "colageno-vitaminas-growth",
    "category": "Suplementos Esportivos",
    "description": "Colágeno + Vitaminas da Growth Supplements, formulado para alta pureza e desempenho.",
    "indication": "Mulheres em geral",
    "usage_instruction": "3 cápsulas ao dia junto ao almoço",
    "ingredients": "Consulte a embalagem oficial para lista completa de ingredientes.",
    "warnings": "Não exceder a recomendação diária de consumo indicada na embalagem.",
    "restrictions": "Alérgicos: consulte a lista de ingredientes no site oficial.",
    "image_url": "",
    "url": "https://www.gsuplementos.com.br/peptideos-de-colageno-vit-a-vit-c-vit-e-zinco-120-comp",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 5,
    "equivalent_slug": null,
    "tags": [],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "gw-24",
    "brand_id": "growth-supplements",
    "brand": "Growth Supplements",
    "name": "Imunno",
    "slug": "imunno-growth",
    "category": "Suplementos Esportivos",
    "description": "Imunno da Growth Supplements, formulado para alta pureza e desempenho.",
    "indication": "Melhora da imunidade",
    "usage_instruction": "Informação não cadastrada",
    "ingredients": "Consulte a embalagem oficial para lista completa de ingredientes.",
    "warnings": "Não exceder a recomendação diária de consumo indicada na embalagem.",
    "restrictions": "Alérgicos: consulte a lista de ingredientes no site oficial.",
    "image_url": "",
    "url": "",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 5,
    "equivalent_slug": null,
    "tags": [
      "saude_geral"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "gw-25",
    "brand_id": "growth-supplements",
    "brand": "Growth Supplements",
    "name": "Melatonina + Associações",
    "slug": "melatonina-associacoes-growth",
    "category": "Suplementos Esportivos",
    "description": "Melatonina + Associações da Growth Supplements, formulado para alta pureza e desempenho.",
    "indication": "Pessoas com dificuldade de dormir",
    "usage_instruction": "3 cápsulas, 30minutos antes de dormir",
    "ingredients": "Consulte a embalagem oficial para lista completa de ingredientes.",
    "warnings": "Não exceder a recomendação diária de consumo indicada na embalagem.",
    "restrictions": "Alérgicos: consulte a lista de ingredientes no site oficial.",
    "image_url": "",
    "url": "https://www.gsuplementos.com.br/melatonina-associacoes-90caps-growth-supplements",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 5,
    "equivalent_slug": null,
    "tags": [
      "sono"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "gw-26",
    "brand_id": "growth-supplements",
    "brand": "Growth Supplements",
    "name": "Taurina",
    "slug": "taurina-growth",
    "category": "Suplementos Esportivos",
    "description": "Taurina da Growth Supplements, formulado para alta pureza e desempenho.",
    "indication": "Pessoas com dificuldade de dormir",
    "usage_instruction": "1 dosador com 200ml de água, de tarde",
    "ingredients": "Consulte a embalagem oficial para lista completa de ingredientes.",
    "warnings": "Não exceder a recomendação diária de consumo indicada na embalagem.",
    "restrictions": "Alérgicos: consulte a lista de ingredientes no site oficial.",
    "image_url": "",
    "url": "https://www.gsuplementos.com.br/taurina-powder-250gr-growth-supplements",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 5,
    "equivalent_slug": "sono-foco",
    "tags": [
      "sono"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "gw-27",
    "brand_id": "growth-supplements",
    "brand": "Growth Supplements",
    "name": "Arginina",
    "slug": "arginina-growth",
    "category": "Suplementos Esportivos",
    "description": "Arginina da Growth Supplements, formulado para alta pureza e desempenho.",
    "indication": "Hipertrofia",
    "usage_instruction": "1 comprimido junto ao almoço e 1 junto à janta",
    "ingredients": "Consulte a embalagem oficial para lista completa de ingredientes.",
    "warnings": "Não exceder a recomendação diária de consumo indicada na embalagem.",
    "restrictions": "Alérgicos: consulte a lista de ingredientes no site oficial.",
    "image_url": "",
    "url": "https://www.gsuplementos.com.br/power-arginine-120caps-growth-supplements-p985923",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 5,
    "equivalent_slug": "arginina",
    "tags": [
      "hipertrofia"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "gw-28",
    "brand_id": "growth-supplements",
    "brand": "Growth Supplements",
    "name": "Whey isolado",
    "slug": "whey-isolado-growth",
    "category": "Suplementos Esportivos",
    "description": "Whey isolado da Growth Supplements, formulado para alta pureza e desempenho.",
    "indication": "Todos com intolerancia a lactose severa",
    "usage_instruction": "misturar 2 dosadores com água",
    "ingredients": "Consulte a embalagem oficial para lista completa de ingredientes.",
    "warnings": "Não exceder a recomendação diária de consumo indicada na embalagem.",
    "restrictions": "Alérgicos: consulte a lista de ingredientes no site oficial.",
    "image_url": "",
    "url": "",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 10,
    "equivalent_slug": null,
    "tags": [
      "lactose",
      "saude_geral"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "of-1",
    "brand_id": "oficial-farma",
    "brand": "Oficial Farma",
    "name": "Omega 3",
    "slug": "omega-3-oficialfarma",
    "category": "Fórmulas & Manipulados",
    "description": "Omega 3 da Oficial Farma, manipulado em farmácia de ponta com matéria-prima certificada.",
    "indication": "Todos",
    "usage_instruction": "Tomar 1 cápsula logo antes do almoço e outra logo antes da janta",
    "ingredients": "Fórmula manipulada com ativos de grau farmacêutico.",
    "warnings": "Uso sob orientação médica ou de profissional habilitado.",
    "restrictions": "Consulte restrições específicas para sua condição de saúde.",
    "image_url": "",
    "url": "https://www.oficialfarma.com.br/omega-1g-dha-50-ultra-60-capsulas",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 8,
    "equivalent_slug": "omega-3",
    "tags": [
      "saude_geral"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "of-2",
    "brand_id": "oficial-farma",
    "brand": "Oficial Farma",
    "name": "Magnesio dimalato",
    "slug": "magnesio-dimalato-oficialfarma",
    "category": "Fórmulas & Manipulados",
    "description": "Magnesio dimalato da Oficial Farma, manipulado em farmácia de ponta com matéria-prima certificada.",
    "indication": "Todos",
    "usage_instruction": "Tomar 1 cápsula no almoço e outra na janta",
    "ingredients": "Fórmula manipulada com ativos de grau farmacêutico.",
    "warnings": "Uso sob orientação médica ou de profissional habilitado.",
    "restrictions": "Consulte restrições específicas para sua condição de saúde.",
    "image_url": "",
    "url": "https://www.oficialfarma.com.br/magnesio-dimalato-300mg-90-capsulas",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 8,
    "equivalent_slug": null,
    "tags": [
      "saude_geral"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "of-3",
    "brand_id": "oficial-farma",
    "brand": "Oficial Farma",
    "name": "Complexo B",
    "slug": "complexo-b-oficialfarma",
    "category": "Fórmulas & Manipulados",
    "description": "Complexo B da Oficial Farma, manipulado em farmácia de ponta com matéria-prima certificada.",
    "indication": "Todos",
    "usage_instruction": "Tomar 1 cápsula no almoço",
    "ingredients": "Fórmula manipulada com ativos de grau farmacêutico.",
    "warnings": "Uso sob orientação médica ou de profissional habilitado.",
    "restrictions": "Consulte restrições específicas para sua condição de saúde.",
    "image_url": "",
    "url": "https://www.oficialfarma.com.br/complexo-b-30-capsulas",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 8,
    "equivalent_slug": "complexo-b",
    "tags": [
      "saude_geral"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "of-4",
    "brand_id": "oficial-farma",
    "brand": "Oficial Farma",
    "name": "CoenzimaQ10",
    "slug": "coenzimaq10-oficialfarma",
    "category": "Fórmulas & Manipulados",
    "description": "CoenzimaQ10 da Oficial Farma, manipulado em farmácia de ponta com matéria-prima certificada.",
    "indication": "Todos",
    "usage_instruction": "Tomar 1 cápsula no almoço e outra na janta",
    "ingredients": "Fórmula manipulada com ativos de grau farmacêutico.",
    "warnings": "Uso sob orientação médica ou de profissional habilitado.",
    "restrictions": "Consulte restrições específicas para sua condição de saúde.",
    "image_url": "",
    "url": "https://www.oficialfarma.com.br/coenzima-q10-100mg-60-capsulas",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 8,
    "equivalent_slug": "coenzima-q10",
    "tags": [
      "saude_geral"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "of-5",
    "brand_id": "oficial-farma",
    "brand": "Oficial Farma",
    "name": "Morosil 500mg + Cactin 500mg",
    "slug": "morosil-500mg-cactin-500mg-oficialfarma",
    "category": "Fórmulas & Manipulados",
    "description": "Morosil 500mg + Cactin 500mg da Oficial Farma, manipulado em farmácia de ponta com matéria-prima certificada.",
    "indication": "Emagrecimento, retenção de líquido, mulheres com celulite e com lipedema",
    "usage_instruction": "Morosil: 1 capsula ao dia. Cactin: 1-4 cápsulas ao dia",
    "ingredients": "Fórmula manipulada com ativos de grau farmacêutico.",
    "warnings": "Uso sob orientação médica ou de profissional habilitado.",
    "restrictions": "Consulte restrições específicas para sua condição de saúde.",
    "image_url": "",
    "url": "https://www.oficialfarma.com.br/morosilr-500mg-60-capsulas-cactin-500mg-60-capsulas",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 8,
    "equivalent_slug": null,
    "tags": [
      "emagrecimento"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "of-6",
    "brand_id": "oficial-farma",
    "brand": "Oficial Farma",
    "name": "KSM",
    "slug": "ksm-oficialfarma",
    "category": "Fórmulas & Manipulados",
    "description": "KSM da Oficial Farma, manipulado em farmácia de ponta com matéria-prima certificada.",
    "indication": "Ansiedade, foco",
    "usage_instruction": "Tomar 1 cápsula, 2 vezes ao dia",
    "ingredients": "Fórmula manipulada com ativos de grau farmacêutico.",
    "warnings": "Uso sob orientação médica ou de profissional habilitado.",
    "restrictions": "Consulte restrições específicas para sua condição de saúde.",
    "image_url": "",
    "url": "https://www.oficialfarma.com.br/ksm-66-300mg-60-capsulas",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 8,
    "equivalent_slug": null,
    "tags": [
      "energia",
      "foco",
      "estresse",
      "ansiedade"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "of-7",
    "brand_id": "oficial-farma",
    "brand": "Oficial Farma",
    "name": "Relora",
    "slug": "relora-oficialfarma",
    "category": "Fórmulas & Manipulados",
    "description": "Relora da Oficial Farma, manipulado em farmácia de ponta com matéria-prima certificada.",
    "indication": "Ansiedade, estresse, compulsão alimentar e vontade de doces",
    "usage_instruction": "Tomar 1 cápsula, 2 vezes ao dia",
    "ingredients": "Fórmula manipulada com ativos de grau farmacêutico.",
    "warnings": "Uso sob orientação médica ou de profissional habilitado.",
    "restrictions": "Consulte restrições específicas para sua condição de saúde.",
    "image_url": "",
    "url": "https://www.oficialfarma.com.br/relora-250mg-60-capsulas-com-selo-de-autenticidade",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 8,
    "equivalent_slug": null,
    "tags": [
      "estresse",
      "ansiedade"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "of-8",
    "brand_id": "oficial-farma",
    "brand": "Oficial Farma",
    "name": "Composto Calmante",
    "slug": "composto-calmante-oficialfarma",
    "category": "Fórmulas & Manipulados",
    "description": "Composto Calmante da Oficial Farma, manipulado em farmácia de ponta com matéria-prima certificada.",
    "indication": "Pessoas com Ansiedade",
    "usage_instruction": "Tomar 2 cápsulas no início da noite",
    "ingredients": "Fórmula manipulada com ativos de grau farmacêutico.",
    "warnings": "Uso sob orientação médica ou de profissional habilitado.",
    "restrictions": "Consulte restrições específicas para sua condição de saúde.",
    "image_url": "",
    "url": "https://www.oficialfarma.com.br/composto-indicado-como-calmante-60-capsulas",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 8,
    "equivalent_slug": null,
    "tags": [
      "estresse",
      "ansiedade"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "of-9",
    "brand_id": "oficial-farma",
    "brand": "Oficial Farma",
    "name": "Glucosamina + Condroitina + CT2 + Ácido Hialurônico",
    "slug": "glucosamina-condroitina-ct2-acido-hialuronico-oficialfarma",
    "category": "Fórmulas & Manipulados",
    "description": "Glucosamina + Condroitina + CT2 + Ácido Hialurônico da Oficial Farma, manipulado em farmácia de ponta com matéria-prima certificada.",
    "indication": "Pessoas com dores articulares ou lesões recentes",
    "usage_instruction": "Tomar 1 cápsula no dia",
    "ingredients": "Fórmula manipulada com ativos de grau farmacêutico.",
    "warnings": "Uso sob orientação médica ou de profissional habilitado.",
    "restrictions": "Consulte restrições específicas para sua condição de saúde.",
    "image_url": "",
    "url": "https://www.oficialfarma.com.br/glucosamina-condroitina-ct-2-acido-hialuronico-30-capsulas",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 8,
    "equivalent_slug": null,
    "tags": [
      "articulacoes"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "of-10",
    "brand_id": "oficial-farma",
    "brand": "Oficial Farma",
    "name": "Composto energético",
    "slug": "composto-energetico-oficialfarma",
    "category": "Fórmulas & Manipulados",
    "description": "Composto energético da Oficial Farma, manipulado em farmácia de ponta com matéria-prima certificada.",
    "indication": "Pessoas com Baixa Energia e disposição",
    "usage_instruction": "Tomar 1 cápsula no Café da Manhã e outra no Lanche da Tarde",
    "ingredients": "Fórmula manipulada com ativos de grau farmacêutico.",
    "warnings": "Uso sob orientação médica ou de profissional habilitado.",
    "restrictions": "Consulte restrições específicas para sua condição de saúde.",
    "image_url": "",
    "url": "https://www.oficialfarma.com.br/composto-auxiliar-no-aumento-de-energia-60-capsulas",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 8,
    "equivalent_slug": null,
    "tags": [
      "energia",
      "foco"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "of-11",
    "brand_id": "oficial-farma",
    "brand": "Oficial Farma",
    "name": "NAC",
    "slug": "nac-oficialfarma",
    "category": "Fórmulas & Manipulados",
    "description": "NAC da Oficial Farma, manipulado em farmácia de ponta com matéria-prima certificada.",
    "indication": "Todos",
    "usage_instruction": "Tomar 1 cápsula no almoço",
    "ingredients": "Fórmula manipulada com ativos de grau farmacêutico.",
    "warnings": "Uso sob orientação médica ou de profissional habilitado.",
    "restrictions": "Consulte restrições específicas para sua condição de saúde.",
    "image_url": "",
    "url": "https://www.oficialfarma.com.br/n-acetil-cisteina-nac-500mg-60-doses",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 8,
    "equivalent_slug": "nac-cisteina",
    "tags": [
      "saude_geral"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "of-12",
    "brand_id": "oficial-farma",
    "brand": "Oficial Farma",
    "name": "Psyllium 500mg",
    "slug": "psyllium-500mg-oficialfarma",
    "category": "Fórmulas & Manipulados",
    "description": "Psyllium 500mg da Oficial Farma, manipulado em farmácia de ponta com matéria-prima certificada.",
    "indication": "Pessoas com intestino preso ou com muita fome ou com colesterol alto ou com glicemia alta",
    "usage_instruction": "Tomar até 3 capsulas 2x ao dia antes as refeições. Ir aumentando gradativamente.",
    "ingredients": "Fórmula manipulada com ativos de grau farmacêutico.",
    "warnings": "Uso sob orientação médica ou de profissional habilitado.",
    "restrictions": "Consulte restrições específicas para sua condição de saúde.",
    "image_url": "",
    "url": "https://www.oficialfarma.com.br/psyllium-500mg-60capsulas",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 8,
    "equivalent_slug": "psyllium",
    "tags": [
      "digestao"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "of-13",
    "brand_id": "oficial-farma",
    "brand": "Oficial Farma",
    "name": "Berberina",
    "slug": "berberina-oficialfarma",
    "category": "Fórmulas & Manipulados",
    "description": "Berberina da Oficial Farma, manipulado em farmácia de ponta com matéria-prima certificada.",
    "indication": "Pessoas com glicemia elevada no sangue",
    "usage_instruction": "Tomar 2 cápsulas no almoço e 2 cápsulas na janta",
    "ingredients": "Fórmula manipulada com ativos de grau farmacêutico.",
    "warnings": "Uso sob orientação médica ou de profissional habilitado.",
    "restrictions": "Consulte restrições específicas para sua condição de saúde.",
    "image_url": "",
    "url": "https://www.oficialfarma.com.br/berberina-500mg-60-doses",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 8,
    "equivalent_slug": null,
    "tags": [],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "of-14",
    "brand_id": "oficial-farma",
    "brand": "Oficial Farma",
    "name": "Enzimas digestivas",
    "slug": "enzimas-digestivas-oficialfarma",
    "category": "Fórmulas & Manipulados",
    "description": "Enzimas digestivas da Oficial Farma, manipulado em farmácia de ponta com matéria-prima certificada.",
    "indication": "Pessoas com dificuldade na digestão ou uso antes de refeições livres ou pessoas em processo de ganho de massa muscular que estão comendo um volume muito grande de comida no dia",
    "usage_instruction": "Tomar 1 cápsula logo antes do almoço e outra logo antes da janta",
    "ingredients": "Fórmula manipulada com ativos de grau farmacêutico.",
    "warnings": "Uso sob orientação médica ou de profissional habilitado.",
    "restrictions": "Consulte restrições específicas para sua condição de saúde.",
    "image_url": "",
    "url": "https://www.oficialfarma.com.br/enzimas-digestivas-60-capsulas",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 8,
    "equivalent_slug": null,
    "tags": [
      "hipertrofia"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "of-15",
    "brand_id": "oficial-farma",
    "brand": "Oficial Farma",
    "name": "ProGo",
    "slug": "progo-oficialfarma",
    "category": "Fórmulas & Manipulados",
    "description": "ProGo da Oficial Farma, manipulado em farmácia de ponta com matéria-prima certificada.",
    "indication": "Emagrecimento e Controle do Apetite",
    "usage_instruction": "Tomar 1 sachê, diluido em agua, após o almoço",
    "ingredients": "Fórmula manipulada com ativos de grau farmacêutico.",
    "warnings": "Uso sob orientação médica ou de profissional habilitado.",
    "restrictions": "Consulte restrições específicas para sua condição de saúde.",
    "image_url": "",
    "url": "https://www.oficialfarma.com.br/progo-1-5g-sabor-laranja-30-saches",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 8,
    "equivalent_slug": null,
    "tags": [
      "emagrecimento"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "of-16",
    "brand_id": "oficial-farma",
    "brand": "Oficial Farma",
    "name": "Espinheira Santa",
    "slug": "espinheira-santa-oficialfarma",
    "category": "Fórmulas & Manipulados",
    "description": "Espinheira Santa da Oficial Farma, manipulado em farmácia de ponta com matéria-prima certificada.",
    "indication": "Pessoas com problemas no estomago e intestino preso",
    "usage_instruction": "Tomar 1 cápsula antes da principal refeição",
    "ingredients": "Fórmula manipulada com ativos de grau farmacêutico.",
    "warnings": "Uso sob orientação médica ou de profissional habilitado.",
    "restrictions": "Consulte restrições específicas para sua condição de saúde.",
    "image_url": "",
    "url": "https://www.oficialfarma.com.br/espinheira-santa-500mg-90-capsulas",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 8,
    "equivalent_slug": null,
    "tags": [
      "digestao"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "of-17",
    "brand_id": "oficial-farma",
    "brand": "Oficial Farma",
    "name": "Termogênico Abelinha",
    "slug": "termogenico-abelinha-oficialfarma",
    "category": "Fórmulas & Manipulados",
    "description": "Termogênico Abelinha da Oficial Farma, manipulado em farmácia de ponta com matéria-prima certificada.",
    "indication": "Emagrecimento",
    "usage_instruction": "Tomar 2 cápsulas no Café da Manhã e 2 cápsulas no Lanche da Tarde",
    "ingredients": "Fórmula manipulada com ativos de grau farmacêutico.",
    "warnings": "Uso sob orientação médica ou de profissional habilitado.",
    "restrictions": "Consulte restrições específicas para sua condição de saúde.",
    "image_url": "",
    "url": "https://www.oficialfarma.com.br/termogenico-abelhinha-120-capsulas/p",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 8,
    "equivalent_slug": null,
    "tags": [
      "emagrecimento"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "of-18",
    "brand_id": "oficial-farma",
    "brand": "Oficial Farma",
    "name": "Cha verde",
    "slug": "cha-verde-oficialfarma",
    "category": "Fórmulas & Manipulados",
    "description": "Cha verde da Oficial Farma, manipulado em farmácia de ponta com matéria-prima certificada.",
    "indication": "Emagrecimento, retenção de líquidos, mulheres com celulite e lipedema",
    "usage_instruction": "Tomar 1 cápsula no Café da Manhã e outra no Lanche da Tarde",
    "ingredients": "Fórmula manipulada com ativos de grau farmacêutico.",
    "warnings": "Uso sob orientação médica ou de profissional habilitado.",
    "restrictions": "Consulte restrições específicas para sua condição de saúde.",
    "image_url": "",
    "url": "https://www.oficialfarma.com.br/cha-verde-500mg-60capsulas",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 8,
    "equivalent_slug": "cha-verde",
    "tags": [
      "emagrecimento"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "of-19",
    "brand_id": "oficial-farma",
    "brand": "Oficial Farma",
    "name": "Complexo Probiótico",
    "slug": "complexo-probiotico-oficialfarma",
    "category": "Fórmulas & Manipulados",
    "description": "Complexo Probiótico da Oficial Farma, manipulado em farmácia de ponta com matéria-prima certificada.",
    "indication": "Pessoas com disbiose, qualquer problema intestinal, e imunidade",
    "usage_instruction": "Tomar 1 cápsula ao acordar",
    "ingredients": "Fórmula manipulada com ativos de grau farmacêutico.",
    "warnings": "Uso sob orientação médica ou de profissional habilitado.",
    "restrictions": "Consulte restrições específicas para sua condição de saúde.",
    "image_url": "",
    "url": "https://www.oficialfarma.com.br/complexo-probiotico-60-capsulas",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 8,
    "equivalent_slug": null,
    "tags": [
      "digestao",
      "saude_geral"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "of-20",
    "brand_id": "oficial-farma",
    "brand": "Oficial Farma",
    "name": "Dimpless",
    "slug": "dimpless-oficialfarma",
    "category": "Fórmulas & Manipulados",
    "description": "Dimpless da Oficial Farma, manipulado em farmácia de ponta com matéria-prima certificada.",
    "indication": "Mulheres com celulite ou lipedema",
    "usage_instruction": "Tomar 1 cápsula no dia",
    "ingredients": "Fórmula manipulada com ativos de grau farmacêutico.",
    "warnings": "Uso sob orientação médica ou de profissional habilitado.",
    "restrictions": "Consulte restrições específicas para sua condição de saúde.",
    "image_url": "",
    "url": "https://www.oficialfarma.com.br/dimpless-40mg-30-capsulas-com-selo-de-autenticidade",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 8,
    "equivalent_slug": null,
    "tags": [],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "of-21",
    "brand_id": "oficial-farma",
    "brand": "Oficial Farma",
    "name": "Maca peruana",
    "slug": "maca-peruana-oficialfarma",
    "category": "Fórmulas & Manipulados",
    "description": "Maca peruana da Oficial Farma, manipulado em farmácia de ponta com matéria-prima certificada.",
    "indication": "Homens com Baixa Libido, mulheres na menopausa ou pessoas com baixa disposição",
    "usage_instruction": "Tomar 2 cápsulas pela manhã",
    "ingredients": "Fórmula manipulada com ativos de grau farmacêutico.",
    "warnings": "Uso sob orientação médica ou de profissional habilitado.",
    "restrictions": "Consulte restrições específicas para sua condição de saúde.",
    "image_url": "",
    "url": "https://www.oficialfarma.com.br/maca-peruana-500mg-120-capsulas",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 8,
    "equivalent_slug": null,
    "tags": [
      "libido"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "of-22",
    "brand_id": "oficial-farma",
    "brand": "Oficial Farma",
    "name": "Tribulus terrestris",
    "slug": "tribulus-terrestris-oficialfarma",
    "category": "Fórmulas & Manipulados",
    "description": "Tribulus terrestris da Oficial Farma, manipulado em farmácia de ponta com matéria-prima certificada.",
    "indication": "Homens com Baixa Libido",
    "usage_instruction": "Tomar 2 cápsulas de manhã e 2 cápsulas de tarde",
    "ingredients": "Fórmula manipulada com ativos de grau farmacêutico.",
    "warnings": "Uso sob orientação médica ou de profissional habilitado.",
    "restrictions": "Consulte restrições específicas para sua condição de saúde.",
    "image_url": "",
    "url": "https://www.oficialfarma.com.br/tribulus-terrestris-500mg-120-doses-40-saponinas",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 8,
    "equivalent_slug": null,
    "tags": [
      "libido"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "of-23",
    "brand_id": "oficial-farma",
    "brand": "Oficial Farma",
    "name": "Testo Black",
    "slug": "testo-black-oficialfarma",
    "category": "Fórmulas & Manipulados",
    "description": "Testo Black da Oficial Farma, manipulado em farmácia de ponta com matéria-prima certificada.",
    "indication": "Homens com Baixa Libido ou com objetivo ganho de massa muscular",
    "usage_instruction": "Tomar 2 cápsulas antes do treino",
    "ingredients": "Fórmula manipulada com ativos de grau farmacêutico.",
    "warnings": "Uso sob orientação médica ou de profissional habilitado.",
    "restrictions": "Consulte restrições específicas para sua condição de saúde.",
    "image_url": "",
    "url": "https://www.oficialfarma.com.br/testo-extreme-black",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 8,
    "equivalent_slug": null,
    "tags": [
      "hipertrofia",
      "libido"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "of-24",
    "brand_id": "oficial-farma",
    "brand": "Oficial Farma",
    "name": "Feno-grego",
    "slug": "feno-grego-oficialfarma",
    "category": "Fórmulas & Manipulados",
    "description": "Feno-grego da Oficial Farma, manipulado em farmácia de ponta com matéria-prima certificada.",
    "indication": "Homens com Baixa Libido",
    "usage_instruction": "Tomar 3 cápsulas junto à uma refeição",
    "ingredients": "Fórmula manipulada com ativos de grau farmacêutico.",
    "warnings": "Uso sob orientação médica ou de profissional habilitado.",
    "restrictions": "Consulte restrições específicas para sua condição de saúde.",
    "image_url": "",
    "url": "https://www.oficialfarma.com.br/feno-grego-1000mg-60-doses",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 8,
    "equivalent_slug": null,
    "tags": [
      "libido"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "of-25",
    "brand_id": "oficial-farma",
    "brand": "Oficial Farma",
    "name": "Hair Complex",
    "slug": "hair-complex-oficialfarma",
    "category": "Fórmulas & Manipulados",
    "description": "Hair Complex da Oficial Farma, manipulado em farmácia de ponta com matéria-prima certificada.",
    "indication": "Pessoas com queixa de queda de cabelo",
    "usage_instruction": "Tomar 1 cápsula, 2 vezes ao dia",
    "ingredients": "Fórmula manipulada com ativos de grau farmacêutico.",
    "warnings": "Uso sob orientação médica ou de profissional habilitado.",
    "restrictions": "Consulte restrições específicas para sua condição de saúde.",
    "image_url": "",
    "url": "https://www.oficialfarma.com.br/suplemento-vitaminico-para-cabelos-e-unhas-hair-complex-60-capsulas",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 8,
    "equivalent_slug": null,
    "tags": [],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "of-26",
    "brand_id": "oficial-farma",
    "brand": "Oficial Farma",
    "name": "Teanina + Cafeína + Rhodiola Rosea",
    "slug": "teanina-cafeina-rhodiola-rosea-oficialfarma",
    "category": "Fórmulas & Manipulados",
    "description": "Teanina + Cafeína + Rhodiola Rosea da Oficial Farma, manipulado em farmácia de ponta com matéria-prima certificada.",
    "indication": "Pessoas com Falta de Foco",
    "usage_instruction": "Tomar 2 cápsulas no almoço",
    "ingredients": "Fórmula manipulada com ativos de grau farmacêutico.",
    "warnings": "Uso sob orientação médica ou de profissional habilitado.",
    "restrictions": "Consulte restrições específicas para sua condição de saúde.",
    "image_url": "",
    "url": "https://www.oficialfarma.com.br/teanina-cafeina-rhodiola-rosea-60-doses",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 8,
    "equivalent_slug": null,
    "tags": [
      "energia",
      "foco"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "of-27",
    "brand_id": "oficial-farma",
    "brand": "Oficial Farma",
    "name": "Saúde Capilar - Actrisave + Saw Palmetto",
    "slug": "saude-capilar-actrisave-saw-palmetto-oficialfarma",
    "category": "Fórmulas & Manipulados",
    "description": "Saúde Capilar - Actrisave + Saw Palmetto da Oficial Farma, manipulado em farmácia de ponta com matéria-prima certificada.",
    "indication": "Pessoas com queixa de queda de cabelo por questão hormonal, seja pelo uso de hormônios ou síndrome do ovário policístico.",
    "usage_instruction": "Actrisave: 1 cápsula ao dia. Saw Palmetto: 2 cápsulas ao dia",
    "ingredients": "Fórmula manipulada com ativos de grau farmacêutico.",
    "warnings": "Uso sob orientação médica ou de profissional habilitado.",
    "restrictions": "Consulte restrições específicas para sua condição de saúde.",
    "image_url": "",
    "url": "https://www.oficialfarma.com.br/kit-saude-capilar-actrisavetm-finasterida-like-saw-palmetto",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 8,
    "equivalent_slug": null,
    "tags": [],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "of-28",
    "brand_id": "oficial-farma",
    "brand": "Oficial Farma",
    "name": "Sossegarte Black",
    "slug": "sossegarte-black-oficialfarma",
    "category": "Fórmulas & Manipulados",
    "description": "Sossegarte Black da Oficial Farma, manipulado em farmácia de ponta com matéria-prima certificada.",
    "indication": "Pessoas com dificuldade de dormir",
    "usage_instruction": "Tomar 2 cápsulas antes de dormir",
    "ingredients": "Fórmula manipulada com ativos de grau farmacêutico.",
    "warnings": "Uso sob orientação médica ou de profissional habilitado.",
    "restrictions": "Consulte restrições específicas para sua condição de saúde.",
    "image_url": "",
    "url": "https://www.oficialfarma.com.br/sossegarte-black",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 8,
    "equivalent_slug": "sono-profundo",
    "tags": [
      "sono"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "of-29",
    "brand_id": "oficial-farma",
    "brand": "Oficial Farma",
    "name": "Glicina",
    "slug": "glicina-oficialfarma",
    "category": "Fórmulas & Manipulados",
    "description": "Glicina da Oficial Farma, manipulado em farmácia de ponta com matéria-prima certificada.",
    "indication": "Pessoas com dificuldade de dormir",
    "usage_instruction": "Tomar 3 cápsulas antes de dormir",
    "ingredients": "Fórmula manipulada com ativos de grau farmacêutico.",
    "warnings": "Uso sob orientação médica ou de profissional habilitado.",
    "restrictions": "Consulte restrições específicas para sua condição de saúde.",
    "image_url": "",
    "url": "https://www.oficialfarma.com.br/glicina-500mg-60-capsulas",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 8,
    "equivalent_slug": "sono-profundo",
    "tags": [
      "sono"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "of-30",
    "brand_id": "oficial-farma",
    "brand": "Oficial Farma",
    "name": "Metilcobalamina + Metilfolato",
    "slug": "metilcobalamina-metilfolato-oficialfarma",
    "category": "Fórmulas & Manipulados",
    "description": "Metilcobalamina + Metilfolato da Oficial Farma, manipulado em farmácia de ponta com matéria-prima certificada.",
    "indication": "Vegetarianos ou veganos",
    "usage_instruction": "Tomar 1 cápsula no Café da Manhã",
    "ingredients": "Fórmula manipulada com ativos de grau farmacêutico.",
    "warnings": "Uso sob orientação médica ou de profissional habilitado.",
    "restrictions": "Consulte restrições específicas para sua condição de saúde.",
    "image_url": "",
    "url": "https://www.oficialfarma.com.br/metilcobalamina-1mg-metilfolato-800mcg-30-capsulas",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 8,
    "equivalent_slug": null,
    "tags": [
      "vegano"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "of-31",
    "brand_id": "oficial-farma",
    "brand": "Oficial Farma",
    "name": "TestoBlack Femme",
    "slug": "testoblack-femme-oficialfarma",
    "category": "Fórmulas & Manipulados",
    "description": "TestoBlack Femme da Oficial Farma, manipulado em farmácia de ponta com matéria-prima certificada.",
    "indication": "Mulheres com Baixa Libido ou baixa disposição",
    "usage_instruction": "Tomar 2 cápsulas antes do treino",
    "ingredients": "Fórmula manipulada com ativos de grau farmacêutico.",
    "warnings": "Uso sob orientação médica ou de profissional habilitado.",
    "restrictions": "Consulte restrições específicas para sua condição de saúde.",
    "image_url": "",
    "url": "https://www.oficialfarma.com.br/testo-black-femme",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 8,
    "equivalent_slug": null,
    "tags": [
      "libido"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "of-32",
    "brand_id": "oficial-farma",
    "brand": "Oficial Farma",
    "name": "FomeControlBlack",
    "slug": "fomecontrolblack-oficialfarma",
    "category": "Fórmulas & Manipulados",
    "description": "FomeControlBlack da Oficial Farma, manipulado em farmácia de ponta com matéria-prima certificada.",
    "indication": "Emagrecimento, Controle do Apetite e diminui vontade de doces",
    "usage_instruction": "Tomar 2 cápsulas no almoço",
    "ingredients": "Fórmula manipulada com ativos de grau farmacêutico.",
    "warnings": "Uso sob orientação médica ou de profissional habilitado.",
    "restrictions": "Consulte restrições específicas para sua condição de saúde.",
    "image_url": "",
    "url": "https://www.oficialfarma.com.br/fome-control-black/p",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 8,
    "equivalent_slug": null,
    "tags": [
      "emagrecimento"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "of-33",
    "brand_id": "oficial-farma",
    "brand": "Oficial Farma",
    "name": "L-Arginina",
    "slug": "l-arginina-oficialfarma",
    "category": "Fórmulas & Manipulados",
    "description": "L-Arginina da Oficial Farma, manipulado em farmácia de ponta com matéria-prima certificada.",
    "indication": "Hipertrofia",
    "usage_instruction": "Tomar 2 cápsulas de estômago vazio",
    "ingredients": "Fórmula manipulada com ativos de grau farmacêutico.",
    "warnings": "Uso sob orientação médica ou de profissional habilitado.",
    "restrictions": "Consulte restrições específicas para sua condição de saúde.",
    "image_url": "",
    "url": "https://www.oficialfarma.com.br/l-arginina-aspartato-500mg-100-capsulas",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 8,
    "equivalent_slug": "arginina",
    "tags": [
      "hipertrofia"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "of-34",
    "brand_id": "oficial-farma",
    "brand": "Oficial Farma",
    "name": "Mioinositol",
    "slug": "mioinositol-oficialfarma",
    "category": "Fórmulas & Manipulados",
    "description": "Mioinositol da Oficial Farma, manipulado em farmácia de ponta com matéria-prima certificada.",
    "indication": "Mulheres com SOP, pessoas com resistência a insulina",
    "usage_instruction": "Tomar 1 sachê, diluido em agua, após a refeição",
    "ingredients": "Fórmula manipulada com ativos de grau farmacêutico.",
    "warnings": "Uso sob orientação médica ou de profissional habilitado.",
    "restrictions": "Consulte restrições específicas para sua condição de saúde.",
    "image_url": "",
    "url": "https://www.oficialfarma.com.br/mio-inositol-2g-30-saches-sabor-laranja",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 8,
    "equivalent_slug": null,
    "tags": [],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  },
  {
    "id": "of-35",
    "brand_id": "oficial-farma",
    "brand": "Oficial Farma",
    "name": "Corebiome Plus",
    "slug": "corebiome-plus-oficialfarma",
    "category": "Fórmulas & Manipulados",
    "description": "Corebiome Plus da Oficial Farma, manipulado em farmácia de ponta com matéria-prima certificada.",
    "indication": "Pessoas com Disbiose ou qualquer dificuldade intestinal",
    "usage_instruction": "Tomar 1 cápsula ao dia",
    "ingredients": "Fórmula manipulada com ativos de grau farmacêutico.",
    "warnings": "Uso sob orientação médica ou de profissional habilitado.",
    "restrictions": "Consulte restrições específicas para sua condição de saúde.",
    "image_url": "",
    "url": "https://www.oficialfarma.com.br/corebiomer-plus-170mg-30-caps",
    "coupon": "BRIGADEIRO",
    "active": true,
    "priority": 8,
    "equivalent_slug": null,
    "tags": [
      "digestao"
    ],
    "created_at": "2026-09-01T00:00:00Z",
    "updated_at": "2026-10-01T00:00:00Z"
  }
];
